In [1]:
import pandas as pd

In [23]:
df = pd.read_csv('xsec_cc.dat', delimiter=" ", header=None)
df["logenergy"]=10**df[0]
df

          0         1         2  3         4         5  6   7  logenergy
0  -0.97954  0.000000  0.000000  0  0.000000  0.000000  0 NaN   0.104824
1  -0.93954  0.000000  0.000000  0  0.000000  0.000000  0 NaN   0.114937
2  -0.89954  0.246185  0.000000  0  0.000000  0.000000  0 NaN   0.126026
3  -0.85954  0.000000  0.000000  0  0.087575  0.000000  0 NaN   0.138185
4  -0.81954  0.168208  0.000000  0  0.000000  0.000000  0 NaN   0.151517
..      ...       ...       ... ..       ...       ... ..  ..        ...
70  1.73012  0.669096  0.684607  0  0.308424  0.303445  0 NaN  53.718020
71  1.79032  0.661357  0.674595  0  0.307325  0.303802  0 NaN  61.704949
72  1.85053  0.694078  0.673215  0  0.302910  0.311621  0 NaN  70.881027
73  1.91073  0.671643  0.663316  0  0.310888  0.308908  0 NaN  81.419794
74  1.97094  0.671950  0.677586  0  0.311679  0.309399  0 NaN  93.527645

[75 rows x 9 columns]

In [2]:
f = open('xsec_cc.dat')

In [6]:
f.readlines()

['-0.97954 0 0 0 0 0 0 \n',
 '-0.93954 0 0 0 0 0 0 \n',
 '-0.89954 0.246185 0 0 0 0 0 \n',
 '-0.85954 0 0 0 0.0875746 0 0 \n',
 '-0.81954 0.168208 0 0 0 0 0 \n',
 '-0.77954 0 0 0 0 0 0 \n',
 '-0.73954 0.30005 0 0 0.053271 0 0 \n',
 '-0.69954 0 0.19523 0 0.0837283 0 0 \n',
 '-0.65954 0.208038 0.421675 0 0.0765574 0.0705436 0 \n',
 '-0.61954 0.294452 0.286933 0 0.12324 0.0617671 0 \n',
 '-0.57954 0.996875 0.626276 0 0.143986 0.0508795 0 \n',
 '-0.53954 0.548275 0.20509 0 0.0990712 0.147863 0 \n',
 '-0.49954 0.55011 0.55634 0 0.076725 0.151458 0 \n',
 '-0.45954 0.446397 0.366665 0 0.129482 0.0845417 0 \n',
 '-0.41954 0.632635 0.528393 0 0.152144 0.171336 0 \n',
 '-0.37954 0.495385 0.72357 0 0.174457 0.0831018 0 \n',
 '-0.33954 0.744508 0.68563 0 0.205045 0.118651 0 \n',
 '-0.29954 0.734444 0.716721 0 0.154405 0.115049 0 \n',
 '-0.25954 0.975346 0.820037 0 0.221854 0.162892 0 \n',
 '-0.21954 0.827747 0.730607 0 0.137574 0.216276 0 \n',
 '-0.17954 0.843882 0.802559 0 0.219098 0.156457 0 \n',
 '-0.13954 0.969343 0.785914 0 0.232067 0.179353 0 \n',
 '-0.0995396 0.854581 0.869018 0 0.197372 0.205556 0 \n',
 '-0.0595396 0.983663 0.859729 0 0.222446 0.217097 0 \n',
 '-0.0195396 0.848757 0.844978 0 0.206551 0.269272 0 \n',
 '0.0204604 0.895109 0.935206 0 0.244448 0.220847 0 \n',
 '0.0604604 0.914452 0.88552 0 0.251869 0.234053 0 \n',
 '0.10046 0.861013 0.898038 0 0.306561 0.267308 0 \n',
 '0.14046 0.907162 0.859193 0 0.327648 0.249762 0 \n',
 '0.18046 0.915319 0.790505 0 0.304417 0.30972 0 \n',
 '0.22046 0.855942 0.820622 0 0.312744 0.327886 0 \n',
 '0.26046 0.851239 0.822063 0 0.29769 0.297029 0 \n',
 '0.30046 0.811347 0.753443 0 0.321081 0.318483 0 \n',
 '0.34046 0.814574 0.783848 0 0.343157 0.287441 0 \n',
 '0.38046 0.701892 0.706742 0 0.319206 0.323875 0 \n',
 '0.42046 0.730912 0.723583 0 0.330698 0.300208 0 \n',
 '0.46046 0.744681 0.684937 0 0.326079 0.311879 0 \n',
 '0.50046 0.671869 0.693044 0 0.312816 0.302996 0 \n',
 '0.54046 0.679336 0.686934 0 0.310585 0.318572 0 \n',
 '0.58046 0.686571 0.649289 0 0.319289 0.314326 0 \n',
 '0.62046 0.678547 0.672604 0 0.316064 0.321525 0 \n',
 '0.66046 0.665436 0.645588 0 0.315613 0.317132 0 \n',
 '0.70046 0.644531 0.625648 0 0.316082 0.305486 0 \n',
 '0.74046 0.658271 0.642218 0 0.311956 0.308582 0 \n',
 '0.78046 0.663491 0.654321 0 0.312508 0.318483 0 \n',
 '0.82046 0.631056 0.631763 0 0.305513 0.302126 0 \n',
 '0.86046 0.66876 0.635257 0 0.308329 0.30127 0 \n',
 '0.90046 0.660338 0.625619 0 0.306087 0.306104 0 \n',
 '0.94046 0.643311 0.657984 0 0.298916 0.301982 0 \n',
 '0.98046 0.625439 0.651158 0 0.298618 0.30663 0 \n',
 '1.01783 0.657996 0.633883 0 0.313243 0.31698 0 \n',
 '1.05277 0.673338 0.658631 0 0.307081 0.287718 0 \n',
 '1.08772 0.677386 0.656375 0 0.317896 0.312298 0 \n',
 '1.12267 0.632252 0.647503 0 0.308008 0.298637 0 \n',
 '1.15762 0.678992 0.637277 0 0.308523 0.294566 0 \n',
 '1.19257 0.723872 0.666305 0 0.315231 0.312198 0 \n',
 '1.22752 0.653322 0.643777 0 0.292162 0.295588 0 \n',
 '1.26247 0.622354 0.673492 0 0.294402 0.301165 0 \n',
 '1.29741 0.686467 0.644381 0 0.298315 0.297741 0 \n',
 '1.33236 0.684287 0.633109 0 0.313327 0.294951 0 \n',
 '1.36731 0.672898 0.684109 0 0.30258 0.293876 0 \n',
 '1.40226 0.653962 0.656779 0 0.294598 0.297095 0 \n',
 '1.43721 0.648497 0.665576 0 0.305063 0.315492 0 \n',
 '1.47216 0.66832 0.650828 0 0.302054 0.307143 0 \n',
 '1.5071 0.675428 0.678639 0 0.306985 0.29573 0 \n',
 '1.54205 0.657458 0.660029 0 0.310615 0.293302 0 \n',
 '1.577 0.676132 0.678055 0 0.301219 0.301008 0 \n',
 '1.61195 0.665774 0.658928 0 0.290102 0.297891 0 \n',
 '1.6469 0.671183 0.664547 0 0.301493 0.305005 0 \n',
 '1.68185 0.661161 0.668346 0 0.303365 0.30314 0 \n',
 '1.73012 0.669096 0.684607 0 0.308424 0.303445 0 \n',
 '1.79032 0.661357 0.674595 0 0.307325 0.303802 0 \n',
 '1.85053 0.694078 0.673215 0 0.30291 0.311621 0 \n',
 '1.91073 0.671643 0.663316 0 0.310888 0.308908 0 \n',
 '1.97094 0.67195 0.677586 0 0.311679 0.309399 0 \n']